# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipingSshd < Formula
  desc "SSH server from anywhere with Piping Server"
  homepage "https://github.com/nwtgck/go-piping-sshd"
  version "0.1.0-release-trigger4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-piping-sshd/releases/download/v0.1.0-release-trigger4/piping-sshd-0.1.0-release-trigger4-darwin-amd64.tar.gz"
    sha256 "1b7fa445b301c319e6db0a38cbc490942162b5367847f11dc010d70647a37bc0"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nwtgck/go-piping-sshd/releases/download/v0.1.0-release-trigger4/piping-sshd-0.1.0-release-trigger4-darwin-arm64.tar.gz"
    sha256 "d5644bf8eeb0a82f481cea27c943996667bc01eba546b5fd56ff3a6fe7b408ac"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-piping-sshd/releases/download/v0.1.0-release-trigger4/piping-sshd-0.1.0-release-trigger4-linux-amd64.tar.gz"
    sha256 "b844def00924e7ce583c98a547d1aae77d68d7f828a03a1a0a1a41d4feb90200"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-piping-sshd/releases/download/v0.1.0-release-trigger4/piping-sshd-0.1.0-release-trigger4-linux-armv6.tar.gz"
    sha256 "9fed0f366031e9b2a7d92c082a71a6cdee2374ad78bdf1fb091441bf8a4e71f3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-piping-sshd/releases/download/v0.1.0-release-trigger4/piping-sshd-0.1.0-release-trigger4-linux-arm64.tar.gz"
    sha256 "6874cb866b2e0c23ad58216372518569d50f0d7889e7c1a8ff4cbf533e3b70b9"
  end

  def install
    bin.install "piping-sshd"
  end
end
